### ISSUE TITLE
User's ability to unsubscribe

### ISSUE THREAD

**Issue by hsb1007** [kuky-com/mobile-app#42]
User should be able to unsubscribe from email. and being able to select which email to unsubscribe from.

THe option would be (for now) 

- Unsubscribe from new connection request

More email type will come in future enhancement

**Comment by tungmt** [comment]
Should we add a checkbox on signup that allow people to subscribe our matching email? Because as I know in some country if we not accepted by customer to send them email that is illegal.

And as I understand this will use for our Social Media lead users, they already accepted to receive an email about matching.

**Comment by hsb1007** [comment]
Yes great point, please add the subscription tick box in both registration / update user profile

**Comment by hsb1007** [comment]
And add push notification subscription button in App setting page. it should direct users to phone's notification page

**Comment by tungmt** [comment]
Yes, sure. We will have it in the app.
